[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.0
    env_list =
        py3{8,9,10,11,12}
    labels =
        py = py3{8,9,10,11,12}

    [testenv]
    skipsdist = true
    deps =
        -r {toxinidir}/requirements-dev.txt
    passenv =
        COVERAGE_*
    commands =
        python -V
        coverage run -p -m pytest {posargs:-qq}

    [testenv:publish]
    skip_install = true
    allowlist_externals =
      rm
      find
      setuptools-golang-bulid-manylinux-wheels
      twine
    commands =
      rm -rf {toxinidir}/build {toxinidir}/dist {toxinidir}/.eggs
      find . -name '*.egg-info' -exec rm -rf {} +
      find . -name '*.egg' -exec rm -rf {} +
      find . -name '*.pyc' -exec rm -f {} +
      find . -name '*.pyo' -exec rm -f {} +
      find . -name '*~' -exec rm -f {} +
      find . -name '__pycache__' -exec rm -fr {} +
      rm -fr .pytest_cache
      setuptools-golang-build-manylinux-wheels --golang="1.21.5" --pythons="cp38-cp38 cp39-cp39"
      python -m build --sdist
      twine check --strict {toxinidir}/dist/*
      twine upload {toxinidir}/dist/* -r pygfried
"""
