name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    environment: release
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Build package
        run: |
          python3 -m pip install --upgrade build twine setuptools-golang
          python3 -m build
          setuptools-golang-build-manylinux-wheels --golang=1.23.10 --pythons=cp39-cp39
          python3 -m twine check --strict dist/*
      - name: Test wheel installation
        shell: bash
        run: |
          python3 -m venv test_env
          source test_env/bin/activate
          pip install dist/*.whl
          python -c "import pygfried; print('Version:', pygfried.version())"
      - name: Upload distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
