name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:

  build:
    name: Build ${{ matrix.os }} package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install build dependencies
        run: python -m pip install --upgrade build twine setuptools-golang wheel setuptools
      - name: Build package
        shell: bash
        run: |
          python -m build
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            setuptools-golang-build-manylinux-wheels --golang=1.23.10 --pythons=cp39-cp39
          fi
          python -m twine check --strict dist/*
      - name: Test wheel installation (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $wheels = Get-ChildItem dist/*.whl
          python -m venv test_env
          .\\test_env\\Scripts\\Activate.ps1
          pip install $wheels[0].FullName
          python -c "import pygfried; print('Version:', pygfried.version())"
          deactivate
      - name: Test wheel installation (macOS/Linux)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          python -m venv test_env
          source test_env/bin/activate
          pip install dist/*.whl
          python -c "import pygfried; print('Version:', pygfried.version())"
          deactivate
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ matrix.os }}
          path: dist/*

  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment: release
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_build_artifacts
      - name: Prepare packages for publishing
        shell: bash
        run: |
          mkdir -p dist
          find all_build_artifacts -type f \( -name '*.whl' -o -name '*.tar.gz' \) -exec cp {} dist/ \;
          echo "Contents of dist/ before publishing:"
          ls -R dist
      - name: Upload distribution packages to PyPI
        id: pypi-publish
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" --generate-notes
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && steps.pypi-publish.outcome == 'success'
